Update README.md
weekly-academy/sumi-assignment pull request #2
Opened 2023-08-28 12:08 UTC by suri-pu-bi

ERD 추가

2023-08-30 03:48 UTC, heli-os commented
@suri-pu-bi 
노션 링크말고 README.md에 바로 작성해주실 수 있을까요?

2023-08-30 03:51 UTC, heli-os requested changes
노션 링크말고 README.md에 바로 작성해주실 수 있을까요?

2023-08-30 14:38 UTC, heli-os requested changes

2023-08-30 14:38 UTC, heli-os commented on README.md
> +  ![ERD](https://github.com/weekly-academy/sumi-assignment/assets/81948599/80b7530c-a421-4825-b9e0-abe4e3406afb)
현재 구조에서는 point의 approved_at 컬럼이 매 사용/적립마다 가장 최신 시점으로 업데이트 될 것으로 보이는데, 이렇게 됐을 때 문제는 없을까요?

만약 해당 point 테이블이 매 사용/적립마다 새롭게 쌓이는 로그성 테이블이라면, 유저의 최종 포인트(현재 포인트)를 계산하려면 어떻게 해야할까요?

2023-08-30 14:38 UTC, heli-os commented on README.md
> +  ![ERD](https://github.com/weekly-academy/sumi-assignment/assets/81948599/80b7530c-a421-4825-b9e0-abe4e3406afb)
구글밋 통해서 이야기한 내용 메모
1. point 테이블은 로그성 테이블
2. 그래서, 현재 포인트를 기록하는 테이블을 한개 더 추가하자.
3. barcode 테이블의 PK는 bigint로 변경하자 -> MySQL 인덱스 원리(정렬) 따로 찾아보면 좋음
4. 테이블 간 양방향 매핑(의존)은 하지말자.

2023-08-30 14:38 UTC, heli-os commented on README.md
> +  - [백엔드 아키텍처 정리한 내용](https://imported-event-228.notion.site/3ee90d9a43ae4223acd9a8e4dcd4cb9a?pvs=4)
레이어드 아키텍처 -> 데이터베이스 주도 설계를 유도해서 문제가 발생할 수 있다고 했는데, 무슨 문제가 발생 할 수 있을까요?

2023-08-30 14:38 UTC, heli-os commented on README.md
> +  - [백엔드 아키텍처 정리한 내용](https://imported-event-228.notion.site/3ee90d9a43ae4223acd9a8e4dcd4cb9a?pvs=4)
클린 아키텍처 -> 왜 의존성 역전을 할까요? 왜 해야 할까요?

2023-08-30 14:38 UTC, heli-os commented on README.md
> +  - [백엔드 아키텍처 정리한 내용](https://imported-event-228.notion.site/3ee90d9a43ae4223acd9a8e4dcd4cb9a?pvs=4)
제 Repository 및 블로그 게시글인데, 한번 둘러보시면 좋을 것 같네요.

https://github.com/heli-os/member-invitation-java-springboot
https://dataportal.kr/74

2023-08-30 14:38 UTC, heli-os commented on README.md
> +        data: PointResponse;
여기는 성공했을 때(200일 때), isSuccess라는 필드가 포함되어 있는데 없는 곳도 있네요. 통일이 필요할 것 같습니다.

필요하다면 RFC 7807 RESTful API 실패에 대한 표준 참고!
 - https://sungyong.medium.com/rfc7807-restful-api-실패에-대한-표준-411a3c369795

2023-08-30 14:41 UTC, heli-os commented
2023.08.30(수) 리뷰 & 일감
1. 테이블 설계, ERD 재작성
2. 레이어드 아키텍처와 클린 아키텍처에 대해서 질문 남긴거 답변 해보기
3. API 명세서 성공/실패의 경우 표준 참고해서 재설계

2023-09-06 09:17 UTC, suri-pu-bi commented on README.md
> +  - [백엔드 아키텍처 정리한 내용](https://imported-event-228.notion.site/3ee90d9a43ae4223acd9a8e4dcd4cb9a?pvs=4)
1. 의존성의 방향이 아래 계층을 향하고, 최하단에는 데이터베이스 관련 레이어가 존재하기 때문에 데이터베이스의 구조를 먼저 생각하고, 이를 토대로 도메인 로직을 구현
-> 도메인 로직을 구성하고, 로직을 제대로 이해했는지 먼저 확인하지 않고, 영속성 계층과 웹 계층을 만들기 때문에 비즈니스 관점에서는 옳지 않은 방법!
2. 영속성 계층과 도메인 계층 사이에 강한 결합을 생기게 하여 변경에 용이하지 않게 된다.

2023-09-06 09:17 UTC, suri-pu-bi commented on README.md
> +  - [백엔드 아키텍처 정리한 내용](https://imported-event-228.notion.site/3ee90d9a43ae4223acd9a8e4dcd4cb9a?pvs=4)
> 레이어드 아키텍처 -> 데이터베이스 주도 설계를 유도해서 문제가 발생할 수 있다고 했는데, 무슨 문제가 발생 할 수 있을까요?

1. 의존성의 방향이 아래 계층을 향하고, 최하단에는 데이터베이스 관련 레이어가 존재하기 때문에 데이터베이스의 구조를 먼저 생각하고, 이를 토대로 도메인 로직을 구현
-> 도메인 로직을 구성하고, 로직을 제대로 이해했는지 먼저 확인하지 않고, 영속성 계층과 웹 계층을 만들기 때문에 비즈니스 관점에서는 옳지 않은 방법!
2. 영속성 계층과 도메인 계층 사이에 강한 결합을 생기게 하여 변경에 용이하지 않게 된다.

2023-09-06 09:40 UTC, suri-pu-bi commented on README.md
> +  - [백엔드 아키텍처 정리한 내용](https://imported-event-228.notion.site/3ee90d9a43ae4223acd9a8e4dcd4cb9a?pvs=4)
> 클린 아키텍처 -> 왜 의존성 역전을 할까요? 왜 해야 할까요?

레이어드 아키텍처의 경우, 영속성 계층(저수준 모듈)에 대한 도메인 계층(고수준 모듈)의 의존성 때문에 영속성 계층을 변경할 때마다 잠재적으로 도메인 계층도 변경해야한다. 인터페이스를 통해 의존성 역전을 하면 저수준 모듈이 변경되더라도 고수준 모듈은 변경되지 않도록 함으로써 유지보수를 조금 더 편하게 할 수 있다.

2023-09-07 13:10 UTC, heli-os commented on README.md
> +    // 실패 400
e.g.

```json
{
  "status": string; // SUCCESS, FAILURE,
  "message": string;
  "details": ...
}
```

2023-09-07 13:31 UTC, heli-os approved these changes
## 리뷰

1. 멀티 모듈 관련 아티클 몇개 읽어보기 -> 깨진 유리창 법칙
    - A -> B -> C로 가야하는데,
    - 누군가가 A -> C로 바로 갔을 때..... 다른 사람도 그걸 따라 할 가능성이 높다.
2. 의존성 방향
    - Controller, Service, Repository 가 있을 때,
    - 일반적으로 생각하는 의존성 방향: Controller <- Service <- Repository
    - 의존성 방향이 틀어지게 되면: Service <- Controller / Repository <- Service
3. 의존성 역전
    - 등장인물: Controller, Service, Repository
    - Controller -> Service(Domain) <- Repository(Persistence)
    - Service(Domain)
      - 의존성 역전을 위한 인터페이스가 존재. (UserRepository)
      - 그 후, Persistence 계층에서 인터페이스를 구현. UserJpaRepository

![Screen Shot 2023-09-07 at 10 27 01 PM](https://github.com/weekly-academy/sumi-assignment/assets/44586666/fd1cee45-b598-46cb-864d-8b9a4ff7ed43)

- '발급된 멤버쉽 바코드는 가족이나 친구끼리 공유가 가능하다'
    - 동시성 이슈/동시성 문제
    - MySQL Isolation level (팬텀 리드)

## 일감

1. point 사용 내역 기록 시 어떤 상점에서 사용되었는지도 기록하기
2. Application Architecture 작성해보기
    - 예제: https://github.com/heli-os/data-provider-client
    - 툴: draw.io / Figma / ... ( https://careerly.co.kr/comments/78482 )

2023-09-07 13:36 UTC, merged