feat: 멤버서비스 구현, entity 연관관계 설정, controller, service, dto 틀 잡기
weekly-academy/sumi-assignment pull request #5
Opened 2023-10-01 07:09 UTC by suri-pu-bi

entity 연관관계 설정, controller, dto, service 로직 틀잡기, 멤버서비스 구현

2023-10-01 07:29 UTC, heli-os requested changes
수고하셨습니다. 리뷰 참고해서 코멘트 or 수정 부탁드려요.

코드 작업을 위해 주어졌던 시간에 비해선 코드 작업량이 터무니없이 적습니다. 보통 2-3일이면 다 완성하시는 수준인데 참고해서 더 열심히 해주세요. :)

2023-10-01 07:29 UTC, heli-os commented on build.gradle
> +}
이제 그루비 형태 build.gradle에서 코틀린 dsl 기반 build.gradle.kts 로 변경되어서 이 플젝에서도 바꿔서 사용해보시죠 :)

https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds

2023-10-01 07:29 UTC, heli-os commented on build.gradle
> +	implementation 'org.apache.commons:commons-lang3:3.12.0'
버전을 build.gradle에 지정하는게 아니라 외부에 지정하는 방법도 있으니 한번 찾아보고 적용해보시면 좋을 것 같습니다.

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/MembershipApplication.java
> +
불필요한 공백이 많이 보이네요. lint 찾아보시고 일괄적으로 적용해보시는걸 추천합니다.

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/application/BarcodeServiceImpl.java
> +//@Slf4j
로그는 적용했다가 주석 처리하신 이유가 있으실까요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/application/BarcodeServiceImpl.java
> +public class BarcodeServiceImpl implements BarcodeService{
BarcodeService Interface와 BarcodeServiceImpl이 같은 위치에 존재하네요.
1개의 인터페이스가 1개의 구현체만 존재하는데, 이것들이 같은 패키지에 있으면 이점이 있을까요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/application/BarcodeServiceImpl.java
> +    public Boolean validateBarcode(String barcodeNumber) throws Exception {
이건 어디서 쓰일 예정인가요? PR을 올려주실 땐 사용되지 않는 부분은 제외하고 올려주세요.

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/infrastructure/Barcode.java
> +@Table(name = "Barcode")
테이블명 / 컬럼명 컨벤션은 이대로 가는걸까요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/infrastructure/Barcode.java
> +    @Builder
빌더를 사용하신 이유가 있나요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/member/application/MemberServiceImpl.java
> +            return new CommonResponse<String>(true, "멤버가 새롭게 바코드를 발급받았습니다.", newBarcodeNumber);
서비스에서 사용자에게 응답될 Http Response 객체를 직접 만드는게 맞을까요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/member/infrastructure/Member.java
> +        Assert.notNull(barcode, "currentPoint must not be null");
Assert를 사용해주셨군요! 혹시 Assert가 어느 시점에 사용되는지 아실까요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/member/infrastructure/MemberPoint.java
> +    // CasCade 설정을 해주고 싶은데 manyToOne은 반대가 되므로 하기 어려움
Member와 MemberPoint가 왜 cascade로 처리되어야 한다고 생각하시나요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/partnerstore/infrastructure/PartnerStoreCategory.java
> +    private char field;
char보다는 enum이 더 낫지 않을까요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/pointhistory/infrastructure/Type.java
> +@RequiredArgsConstructor
이 어노테이션이 필요한가요?

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/pointhistory/infrastructure/PointHistory.java
> +    private LocalDateTime approvedAt;
Instant나 OffsetDateTime, ZonedDateTime 같은걸 사용 할 수 있는 방법을 찾아보시면 좋을 것 같아요.

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/pointhistory/infrastructure/PointHistory.java
> +    private PartnerStore partnerStore;
지금 구조라면 의존하고 있는 원천 테이블이 변경 될 때 PointHistory도 영향 받을 수 있는데, 문제 없을까요?

1. 2023-10-01 10:00:00 > 파리바게트 강남점에서 10,000원 적립
2. 파리바게트 강남점 상호명을 '파리바게트 강남 파리오브랩 특별 지점'으로 변경
3. 내역에서 '파리바게트 강남점'이 '파리바게트 강남 파리오브랩 특별 지점'으로 바뀜

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/pointhistory/application/PointHistoryService.java
> +    CommonResponse<List<PointResponse>> getPointHistoryList(LocalDateTime starTime, LocalDateTime endTime, String barcode);
메소드 명이나 변수명에 ~List 같이 자료형을 포함할 필요는 없어 보입니다.

2023-10-01 07:29 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/partnerstore/application/PartnerServiceImpl.java
> +    }
메소드 파라미터와 반환 값으로 primitive 타입이 아니라 wrapper 타입을 사용하신 이유가 있으실까요?

2023-10-14 14:20 UTC, suri-pu-bi commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/application/BarcodeServiceImpl.java
> +public class BarcodeServiceImpl implements BarcodeService{
이거에 대해서 찾아보고 블로그에 정리해봤습니다! https://velog.io/@kirise/Spring-Service-ServiceImpl-%EA%B5%AC%EC%A1%B0%EA%B0%80-%EA%B3%BC%EC%97%B0-%ED%95%84%EC%9A%94%ED%95%A0%EA%B9%8C

2023-10-14 14:25 UTC, suri-pu-bi commented on src/main/java/com/mentoring/assignment/membership/domain/barcode/infrastructure/Barcode.java
> +@Table(name = "Barcode")
JPA Naming에 관련해서 찾아봤는데 테이블명,컬럼명은 소문자, 언더스코어를 사용해서 "barcode", "partner_category"로 수정했습니다!

2023-10-14 14:39 UTC, suri-pu-bi commented on src/main/java/com/mentoring/assignment/membership/domain/partnerstore/application/PartnerServiceImpl.java
> +    }
이것에 대해 찾아봤습니다! 🥹
primitive Type은 null 허용하지 않고, false/true 만 가능합니다. null 허용하지 않기 때문에 @NotNull이 동작하지 않게 되고, getter 사용시 isXXX로 꺼내기 때문에 ' is' 를 필드에 붙일 시 이름이 원하는대로 표시되지 않을 수 있습니다. 
하지만 WrapperClass은 nul을 허용하기 때문에 @Notnull도 정상적으로 작동이 되고, getter 사용시 get으로 꺼내기 때문에 이름문제도 정상적으로 작동이 됩니다. 
그런 이유에서 메소드 파라미터와 반환값, Request 등도 null이 들어올 가능성이 있다고 판단해서 Wrapper Type을 사용하였습니다!

2023-10-14 14:40 UTC, suri-pu-bi commented on src/main/java/com/mentoring/assignment/membership/domain/pointhistory/application/PointHistoryService.java
> +    CommonResponse<List<PointResponse>> getPointHistoryList(LocalDateTime starTime, LocalDateTime endTime, String barcode);
이 부분은 수정완료했습니다!

2023-10-14 14:43 UTC, suri-pu-bi commented on src/main/java/com/mentoring/assignment/membership/domain/pointhistory/infrastructure/PointHistory.java
> +    private LocalDateTime approvedAt;
https://devlopsquare.tistory.com/248
https://dev-minjeong.tistory.com/31

다음 두 블로그를 읽고 참고해서 OffsetDateTime으로 변경하였습니다!

2023-10-14 14:44 UTC, suri-pu-bi commented on src/main/java/com/mentoring/assignment/membership/domain/partnerstore/infrastructure/PartnerStoreCategory.java
> +    private char field;
Field라는 enum으로 변경하였습니다!

2023-10-15 12:59 UTC, heli-os commented on src/main/java/com/mentoring/assignment/membership/domain/partnerstore/application/PartnerServiceImpl.java
> +    }
partnerId가 null이 되는 경우가 있나요?

2023-10-15 13:00 UTC, heli-os approved these changes
@suri-pu-bi 
완료된 코멘트는 resolve 처리 해주시고, 이 PR은 머지해주세요.

2023-10-15 18:14 UTC, merged